-- 经过真值数据核对的复杂业务语义；仅声明口径与结果形态，不存储可执行 SQL。
INSERT INTO semantic_contracts (
  id, contract_key, version, contract_type, display_name, business_definition,
  source_tables, source_fields, synonyms, aggregation, semantic_config, owner, status
)
VALUES
  (gen_random_uuid(), 'order_time_range', 1, 'metric', '订单数据时间范围', '订单创建时间的最早和最晚日期，用于描述订单数据覆盖范围。', ARRAY['orders'], ARRAY['orders.created_at'], ARRAY['订单数据的时间范围','订单时间范围','订单数据覆盖时间'], 'min_max', '{"plan":{"measures":[{"name":"order_time_range","operation":"min_max"}],"expected_columns":["min_order_at","max_order_at"],"expected_row_shape":"single"}}'::jsonb, 'data-team', 'enabled'),
  (gen_random_uuid(), 'category_sales_ranking', 1, 'metric', '品类销售额排行', '按商品品类汇总订单商品明细售价，并按销售额从高到低排行。', ARRAY['order_items','products'], ARRAY['order_items.price','order_items.product_id','products.id','products.category'], ARRAY['销售额最高的品类','品类销售额排行','品类卖得最多'], 'sum', '{"plan":{"measures":[{"name":"category_sales_amount","operation":"sum"}],"dimensions":["category"],"order_by":["category_sales_amount DESC"],"limit":5,"expected_columns":["category","category_sales_amount"],"expected_row_shape":"ranking"}}'::jsonb, 'data-team', 'enabled'),
  (gen_random_uuid(), 'category_item_count_ranking', 1, 'metric', '品类订单商品数排行', '按商品品类统计订单商品明细数，并按数量从高到低排行。', ARRAY['order_items','products'], ARRAY['order_items.id','order_items.product_id','products.id','products.category'], ARRAY['订单商品数最多的品类','品类商品数排行'], 'count', '{"plan":{"measures":[{"name":"order_item_count","operation":"count"}],"dimensions":["category"],"order_by":["order_item_count DESC"],"limit":5,"expected_columns":["category","order_item_count"],"expected_row_shape":"ranking"}}'::jsonb, 'data-team', 'enabled'),
  (gen_random_uuid(), 'product_sales_ranking', 1, 'metric', '商品销售额排行', '按订单商品明细的商品标识汇总售价，并按销售额从高到低排行。', ARRAY['order_items'], ARRAY['order_items.product_id','order_items.price'], ARRAY['销售额最高的商品','销售额最高的商品 ID','商品销售额排行'], 'sum', '{"plan":{"measures":[{"name":"product_sales_amount","operation":"sum"}],"dimensions":["product"],"order_by":["product_sales_amount DESC"],"limit":5,"expected_columns":["product_id","product_sales_amount"],"expected_row_shape":"ranking"}}'::jsonb, 'data-team', 'enabled'),
  (gen_random_uuid(), 'average_product_weight', 1, 'metric', '商品平均重量', '全部商品重量字段的平均值，单位为克。', ARRAY['products'], ARRAY['products.weight_g'], ARRAY['商品平均重量','平均商品重量','平均重量是多少克'], 'avg', '{"plan":{"measures":[{"name":"avg_weight_g","operation":"average"}],"expected_columns":["avg_weight_g"],"expected_row_shape":"single"}}'::jsonb, 'data-team', 'enabled'),
  (gen_random_uuid(), 'freight_total', 1, 'metric', '订单商品运费总额', '订单商品明细 freight_value 的累计金额。', ARRAY['order_items'], ARRAY['order_items.freight_value'], ARRAY['订单商品运费总额','运费总额'], 'sum', '{"plan":{"measures":[{"name":"freight_total","operation":"sum"}],"expected_columns":["freight_total"],"expected_row_shape":"single"}}'::jsonb, 'data-team', 'enabled'),
  (gen_random_uuid(), 'refund_amount_total', 1, 'metric', '退款总金额', '退款记录 amount 的累计金额。', ARRAY['refunds'], ARRAY['refunds.amount'], ARRAY['退款总金额','退款金额'], 'sum', '{"plan":{"measures":[{"name":"refund_amount","operation":"sum"}],"expected_columns":["refund_amount"],"expected_row_shape":"single"}}'::jsonb, 'data-team', 'enabled'),
  (gen_random_uuid(), 'average_review_score', 1, 'metric', '平均评价分', '评价记录 score 的平均值。', ARRAY['reviews'], ARRAY['reviews.score'], ARRAY['平均评价分','平均评分'], 'avg', '{"plan":{"measures":[{"name":"avg_review_score","operation":"average"}],"expected_columns":["avg_review_score"],"expected_row_shape":"single"}}'::jsonb, 'data-team', 'enabled'),
  (gen_random_uuid(), 'review_score_distribution', 1, 'metric', '评价分布', '按评价分数分组统计评价记录数量。', ARRAY['reviews'], ARRAY['reviews.score','reviews.id'], ARRAY['各评价分数量','评价分数量','评价分布'], 'count', '{"plan":{"measures":[{"name":"review_count","operation":"count"}],"dimensions":["review_score"],"expected_columns":["score","review_count"],"expected_row_shape":"grouped"}}'::jsonb, 'data-team', 'enabled'),
  (gen_random_uuid(), 'user_state_ranking', 1, 'dimension', '州用户数排行', '按用户州字段统计用户数，并按数量从高到低排行。', ARRAY['users'], ARRAY['users.id','users.state'], ARRAY['用户数最多的州','州用户数排行'], 'count', '{"plan":{"measures":[{"name":"user_count","operation":"count_distinct"}],"dimensions":["state"],"order_by":["user_count DESC"],"limit":5,"expected_columns":["state","user_count"],"expected_row_shape":"ranking"}}'::jsonb, 'data-team', 'enabled'),
  (gen_random_uuid(), 'user_city_ranking', 1, 'dimension', '城市用户数排行', '按用户城市字段统计用户数，并按数量从高到低排行。', ARRAY['users'], ARRAY['users.id','users.city'], ARRAY['用户数最多的城市','城市用户数排行'], 'count', '{"plan":{"measures":[{"name":"user_count","operation":"count_distinct"}],"dimensions":["city"],"order_by":["user_count DESC"],"limit":5,"expected_columns":["city","user_count"],"expected_row_shape":"ranking"}}'::jsonb, 'data-team', 'enabled'),
  (gen_random_uuid(), 'late_delivery_order_total', 1, 'metric', '晚于预计送达日期订单数', '已送达且实际送达时间晚于预计送达时间的订单数量。', ARRAY['orders'], ARRAY['orders.id','orders.delivered_customer_at','orders.estimated_delivery_at'], ARRAY['晚于预计送达日期的订单数','延迟送达订单数'], 'count', '{"plan":{"measures":[{"name":"late_delivery_order_count","operation":"count"}],"expected_columns":["late_delivery_order_count"],"expected_row_shape":"single"}}'::jsonb, 'data-team', 'enabled')
ON CONFLICT (contract_key, version) DO NOTHING;
